version: 2.1

workflows:
  on_commit:
    jobs:
      - py38
      - py37
      - py36
  nightly:
    jobs:
      - py38
      - py37
      - py36
    triggers:
      - schedule:
          cron: "1 1 * * *"
          filters:
            branches:
              only:
                - main
  release:
    jobs:
      - py38
      - py37
      - upload_private_packages_py37:
          context:
            - AWS harper package pusher
          requires:
            - py37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - upload_private_packages_py38:
          context:
            - AWS harper package pusher
          requires:
            - py38
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

# run_tests is a template used by the jobs in jobs:
commands:
  run_tests:
    description: "Checkout, restore cache / build cache, run tests, cache"
    parameters:
      python_version:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-<< parameters.python_version >>-{{ checksum "dev-requirements.txt" }}

      - run:
          name: "Install tox"
          command: |
            pip install tox

      - run:
          name: "Run tests"
          command: |
            tox -e << parameters.python_version >>

      - save_cache:
          key: dependencies-<< parameters.python_version >>-{{ checksum "dev-requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - ".tox"

  build_and_upload_private_packages:
    description: "Build packages and upload packages to private repository"
    parameters:
      python_version:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-<< parameters.python_version >>-{{ checksum "dev-requirements.txt" }}

      - run:
          name: "make private release"
          command: |
            pip install -r dev-requirements.txt .
            pip install "awscli>=1.8"
            make upload-private-release

      - save_cache:
          key: dependencies-<< parameters.python_version >>-{{ checksum "dev-requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - ".tox"

jobs:
  upload_private_packages_py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - build_and_upload_private_packages:
          python_version: "py37"

  upload_private_packages_py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - build_and_upload_private_packages:
          python_version: "py38"

  py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - run_tests:
          python_version: "py38-airflow"

  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - run_tests:
          python_version: "py37-airflow"

  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run_tests:
          python_version: "py36-airflow"
