version: 2.1

workflows:
  push_test:
    jobs:
      - private_push:
          context:
            - AWS harper package pusher

  on_commit:
    jobs:
      - py38
      - py37
      - py36
      - py36-compat-1-10-2
      - py36-compat-1-10-6
  nightly:
    jobs:
      - py38
      - py37
      - py36
      - py36-compat-1-10-2
      - py36-compat-1-10-6
    triggers:
      - schedule:
          cron: "1 1 * * *"
          filters:
            branches:
              only:
                - main

# run_tests is a template used by the jobs in jobs:
commands:
  run_tests:
    description: "Checkout, restore cache / build cache, run tests, cache"
    parameters:
      python_version:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-<< parameters.python_version >>-{{ checksum "dev-requirements.txt" }}

      - run:
          name: "private release"
          command: |
            python -m pip cache info
            pip install -r dev-requirements.txt .
            pip install "awscli>=1.8"
            make upload-private-release

      - save_cache:
          key: dependencies-<< parameters.python_version >>-{{ checksum "dev-requirements.txt" }}
          paths:
            - ".cache/pip"
            - ".tox"

jobs:
  private_push:
    docker:
      - image: circleci/python:3.8
    steps:
      - run_tests:
          python_version: "py38-airflow"

  py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - run_tests:
          python_version: "py38-airflow"

  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - run_tests:
          python_version: "py37-airflow"

  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run_tests:
          python_version: "py36-airflow"

  py36-compat-1-10-2:
    docker:
      - image: circleci/python:3.6
    steps:
      - run_tests:
          python_version: "py36-airflow1.10.2"

  py36-compat-1-10-6:
    docker:
      - image: circleci/python:3.6
    steps:
      - run_tests:
          python_version: "py36-airflow1.10.6"
