version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: testing-airflow-spell
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
            - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__PLUGINS_FOLDER=/usr/local/airflow/plugins
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ../dags:/usr/local/airflow/dags
            - ../src:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
        command: |
            /bin/bash -c "
                airflow db init
                airflow scheduler -D &
                airflow webserver
            "
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
