version: '3.7'
services:
    webserver:
        image: testing-airflow-spell
        environment:
            - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
            - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ../dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
        command: |
            /bin/bash -c "
                airflow initdb
                airflow scheduler -D &
                airflow webserver
            "
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
